#pragma once

#include <stdint.h>

#include "ChannelInfo.h"

// Channel frames: PNGs in flash. The implementation is generated by
// art/build.py into src/generated/Frames.cpp; rerun it after editing scenes.
struct FrameImage {
    const uint8_t *png;
    uint32_t size;
};

extern const ChannelInfo kChannels[];
extern const uint8_t kChannelCount;

const FrameImage &frameImage(uint8_t channel, uint8_t frame);
